### ISSUE TITLE
是否会有计划将项目部署在gitbook上

### ISSUE THREAD

**Issue by cooktea** [CnTransGroup/EffectiveModernCppChinese#110]
markdown阅读起来还是比较繁琐，尤其是目录置顶的设计对于快速跳转不是很友好。想请问下是否会有计划将项目部署在类似gitbook之类阅读体验比较友好的平台上。

**Comment by kelthuzadx** [comment]
抱歉，个人暂无计划。

如果你感兴趣并愿意持续维护，你可以考虑帮助本项目部署到gitbook。
