### ISSUE TITLE
pdf 版的一个小错误 虽然deleted寒暑假不能被使⽤，它它们还是存在于你的程序中。

### ISSUE THREAD

**Issue by SongZihui-sudo** [CnTransGroup/EffectiveModernCppChinese#121]
![图片](https://user-images.githubusercontent.com/77034643/166866577-6c9c7ca2-3b89-425f-bfd0-04b6ce9fc121.png)

应该是 `虽然deleted函数不能被使用，但它们还是存在于你的程序中。`

**Comment by wendajiang** [comment]
pdf 版本较为滞后，目前支持实时同步 online
