### ISSUE TITLE
或许可以重新做一份中文pdf整合了？

### ISSUE THREAD

**Issue by Alpacabla** [CnTransGroup/EffectiveModernCppChinese#123]
发现中文合集都是去年1月的事情了，这中间的修改还挺多的，所以希望管理员可以重新上传一份中文整合？因为我并不知道具体格式（中文或者字体啥的问题？）所以并不好个人制作一份commit上去。

**Comment by wendajiang** [comment]
已经支持了在线浏览，个人理解 pdf 需求不是很必要，先关闭 issue

如果有什么问题，可以 reopen 这个 issue
