### ISSUE TITLE
提供一个基于当前网页的生成的pdf版,主要是带书签,方便浏览

### ISSUE THREAD

**Issue by gooker** [CnTransGroup/EffectiveModernCppChinese#130]
[Effective Modern C++11_14.pdf](https://github.com/CnTransGroup/EffectiveModernCppChinese/files/9738810/Effective.Modern.C%2B%2B11_14.pdf)
<img width="702" alt="1665219513164" src="https://user-images.githubusercontent.com/5688076/194699319-f1976732-c90b-4837-ab1c-823593a0471b.png">

**Comment by kelthuzadx** [comment]
感谢贡献，方便的话可以提一个PR;-

**Comment by madjxatw** [comment]
网页版打印生成的PDF美观程度不如仓库中的版本，我想了解一下目前仓库中的PDF的制作流程，或许可以帮忙生成一份新的。

**Comment by youncyb** [comment]
> [Effective Modern C++11_14.pdf](https://github.com/CnTransGroup/EffectiveModernCppChinese/files/9738810/Effective.Modern.C%2B%2B11_14.pdf) <img alt="1665219513164" width="702" src="https://user-images.githubusercontent.com/5688076/194699319-f1976732-c90b-4837-ab1c-823593a0471b.png">

这是怎么生成的？

**Comment by gooker** [comment]
> > [Effective Modern C++11_14.pdf](https://github.com/CnTransGroup/EffectiveModernCppChinese/files/9738810/Effective.Modern.C%2B%2B11_14.pdf) <img alt="1665219513164" width="702" src="https://user-images.githubusercontent.com/5688076/194699319-f1976732-c90b-4837-ab1c-823593a0471b.png">
> 
> 这是怎么生成的？

太久不记得用的那个pdf工具 需要自己手动设置的
