### ISSUE TITLE
Item 3 `names` 翻译歧义

### ISSUE THREAD

**Issue by luoshi006** [CnTransGroup/EffectiveModernCppChinese#133]
根据原文：
> Declarations introduce **names** and types without giving details

`names` 在后续的翻译中应该是 **变量名**，直译为名字不太合适。

![image](https://user-images.githubusercontent.com/13827278/200486877-5a0537fc-b3c6-4071-9e2c-76783b529ae9.png)

_src_: https://github.com/CnTransGroup/EffectiveModernCppChinese/blob/master/src/1.DeducingTypes/item3.md?plain=1#L176

**Comment by y1yang0** [comment]
Thanks, [fixed](https://github.com/CnTransGroup/EffectiveModernCppChinese/commit/305485e38eaefe70584ce7a8a898afbb5416dc22)
