### ISSUE TITLE
Item5 错别字

### ISSUE THREAD

**Issue by luoshi006** [CnTransGroup/EffectiveModernCppChinese#134]
原文： `The last two examples` 

![image](https://user-images.githubusercontent.com/13827278/200717997-2281b368-6c96-43a1-9971-95ff69ae9fda.png)

src: https://github.com/CnTransGroup/EffectiveModernCppChinese/blob/master/src/2.Auto/item5.md?plain=1#L131

**Comment by y1yang0** [comment]
Thanks, [fixed](https://github.com/CnTransGroup/EffectiveModernCppChinese/commit/305485e38eaefe70584ce7a8a898afbb5416dc22)
