### ISSUE TITLE
Item 11 错别字

### ISSUE THREAD

**Issue by luoshi006** [CnTransGroup/EffectiveModernCppChinese#135]
![image](https://user-images.githubusercontent.com/13827278/201631191-cd682ec3-ce68-4d43-8244-ee332debdf77.png)

src: https://github.com/CnTransGroup/EffectiveModernCppChinese/blob/master/src/3.MovingToModernCpp/item11.md?plain=1#L96

**Comment by y1yang0** [comment]
Thanks, [fixed](https://github.com/CnTransGroup/EffectiveModernCppChinese/commit/305485e38eaefe70584ce7a8a898afbb5416dc22)
