### ISSUE TITLE
[Item 1] 语句不通顺

### ISSUE THREAD

**Issue by tmgj** [CnTransGroup/EffectiveModernCppChinese#138]
item1一开始，如下图
![image](https://user-images.githubusercontent.com/17828279/211851225-f625fc75-a53e-4a22-bff8-0d9d65fe6915.png)
红框中，改为：
`ParamType`是一个通用引用
更好一些。

**Comment by y1yang0** [comment]
Thanks, [fixed](https://github.com/CnTransGroup/EffectiveModernCppChinese/commit/305485e38eaefe70584ce7a8a898afbb5416dc22)
