### ISSUE TITLE
Item16: 存在错误 std::mutex 与 std::atomic 均不可复制或移动构造

### ISSUE THREAD

**Issue by Patricky-Tau** [CnTransGroup/EffectiveModernCppChinese#154]
即如下两行存在错误。

- [item16.md#L84](https://github.com/CnTransGroup/EffectiveModernCppChinese/blob/master/src/3.MovingToModernCpp/item16.md?plain=1#L84)
- [item16.md#L105](https://github.com/CnTransGroup/EffectiveModernCppChinese/blob/master/src/3.MovingToModernCpp/item16.md?plain=1#L105)

作者在其 [勘误网站](https://www.aristeia.com/BookErrata/emc++-errata.html#:~:text=Neither%20std%3A%3Amutex%20nor%20std%3A%3Aatomics%20are%20move%2Donly.%20They%20%20%20%20%20%203/25/15%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20106%20%20%20%20%20%20%20are%20neither%20copyable%20nor%20movable%2C%20so%20classes%20containing%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20108%20%20%20%20%20%20%20them%20are%20rendered%20both%20uncopyable%20and%20unmovable.) 上甚至用红字标明了这一点，可见其重要性。

![image](https://user-images.githubusercontent.com/105474676/234373287-7b735149-85b2-4bca-98bb-5296ed7eaa20.png)

**Comment by wendajiang** [comment]
欢迎提出 PR 修正 :)

**Comment by Patricky-Tau** [comment]
qwq 俺改完了，你看看呢 @wendajiang [/pull/155](https://github.com/CnTransGroup/EffectiveModernCppChinese/pull/155)
