### ISSUE TITLE
Item2 抄写错误

### ISSUE THREAD

**Issue by zgjsxx** [CnTransGroup/EffectiveModernCppChinese#157]
这里是原版英文中的第二节的文字:
the type specifier is const auto. And here,
```cpp
const auto& rx = x;
```
这里是翻译后的文字
类型说明符是const auto。另一个：
```cpp
const auto & rx=cx;
```
可以看到原版是```const auto& rx = x;```，翻译后是```const auto & rx=cx```，
这里抄写错误，建议修改

**Comment by standback** [comment]
fixed with #174
