### ISSUE TITLE
Chapter 2 intro翻译问题

### ISSUE THREAD

**Issue by jl4386** [CnTransGroup/EffectiveModernCppChinese#165]
`Using it saves typing, sure, but it also prevents correctness and performance issues that can bedevil manual type declarations` 应该是指`auto`比起手动声明类型，避免了正确性和性能问题，而非相反。

**Comment by Jebearssica** [comment]
额外补充，`because falling back on manual type declarations is an alternative that’s often best avoided.` 中的 manual type 应该指的是手动补全类型，而不应该直接翻译成 manual —— 手册

**Comment by standback** [comment]
> `Using it saves typing, sure, but it also prevents correctness and performance issues that can bedevil manual type declarations` 应该是指`auto`比起手动声明类型，避免了正确性和性能问题，而非相反。

的确是有翻的有问题。
可以上个pr改一下
