### ISSUE TITLE
Chapter3 Item12  多处重载应该为重写

### ISSUE THREAD

**Issue by MingweiYan** [CnTransGroup/EffectiveModernCppChinese#64]
有三处重载 应该修改为重写   

1.  Item 12:使⽤override声明重载函数
2.  条款12：使⽤override声明重载函数
3. 记住：
       为重载函数加上override

**Comment by kelthuzadx** [comment]
目前我没有时间，如果您感兴趣或者其他贡献者感兴趣，欢迎对这部分进行修正。

**Comment by cellspace** [comment]
最近在看，我可以改下。

**Comment by wizardforcel** [comment]
override 最好翻译【覆盖】和rewrite区分开
