### ISSUE TITLE
想生成 mobi 格式的 有啥建议吗

### ISSUE THREAD

**Issue by Aaaaaaron** [CnTransGroup/EffectiveModernCppChinese#99]

**Comment by linwanxiaoyehua** [comment]
先将md导出为epub，然后epub转mobi

**Comment by wendajiang** [comment]
目前在线使用 mdbook 生成 html， 有插件 `mdbook-epub` 生成 epub 文件，可以使用 calibre 将 epub 转换为 mobi

-----
PS. 已经支持在线

**Comment by wendajiang** [comment]
目前在线使用 mdbook 生成 html， 有插件 `mdbook-epub` 生成 epub 文件，可以使用 calibre 将 epub 转换为 mobi

-----
PS. 已经支持在线
